### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by francisdb** [EngineersNeedArt/TeachersPet_VPX#1]
I suggest to add a link in the readme to https://engineersneedart.com/blog/teacherspet/teacherspet.html or copy the blog posts in this repo.

Some other info that might interest you as developer

Flux/mpcarr is assembling different reusable vbs files (like libraries) into a single one. See
https://github.com/mpcarr/CyberRace
The table can be found at https://vpuniverse.com/files/file/17837-cyber-race-flux-original-2023/

For his new table he's even using [vpxtool](https://github.com/francisdb/vpxtool) to keep track of vpx changes
https://github.com/mpcarr/aztec-quest

https://github.com/jsm174/vpx-standalone-scripts contains many scripts and can be useful if you want to search existing code for how to do things.

Thanks for the blog posts!

**Comment by francisdb** [comment]
Would also rename the file from `.txt` to `.vbs` so they get proper styling in github.

**Comment by francisdb** [comment]
You don't need to copy paste from the vpinball editor. VPinball supports sidecar vbs scripts run `vpinball -extractvbs [tablename].vpx` and you you'll have the script next to the table named `[tablename].vbs`. Whenever you run the table it will use that script instead of the one in the vpx. Once everything is ready for release you can copy the contents to the vpinball editor or use `vpxtool` which has a `importvbs` command.

**Comment by francisdb** [comment]
VPinball is no longer focusing on DirectX but more towards OpenGL and Vulkan through https://github.com/bkaradzic/bgfx
There is a Linux/Mac/Android/iOS version of vpinball named VPinball Standalone. It's not some science project and pretty complete these days. Only PuP Pack support is a bit lacking.

**Comment by francisdb** [comment]
There is a code formatter available (have bot used it)
https://gitlab.com/PDStig/vpin-workshop-code-formatter/-/blob/master/vpw-code-format.js

**Comment by francisdb** [comment]
See https://gitlab.com/PDStig/vpin-workshop-scripts for another repo of scripts

**Comment by EngineersNeedArt** [comment]
Thanks for the info. I will indeed put links in the README to the various parts of the blog for which this repo was created. I had only thought of the primary direction before: blog readers going to repo, not the reverse: repo "stumblers" wanting to find the blog that references it.

(Also, I only just reached a milestone in the series — a good point at which to update.)

I may well change the `.txt` extensions to `.vbs` for Github's sake. As I mentioned though, `.bas` were causing my Windows install to act like I was downloading/opening nitroglycerine — seemingly due merely to the extension. I don't want anyone new to scripting to also have these extra (and scary) hurdles put in front of them due to Windows paranoia.

As I mentioned in the other Issue, I have to fix up the links in my blog if I rename a file.

> VPinball supports sidecar vbs scripts

That is news to me. That also would seem like a power-user feature that, if I test it out, I could mention in a sort of "block quote" in the blog (not probably most users would know how to do?).

> It's not some science project and pretty complete these days.

Ha ha, okay. I had someone else call me out about that comment as well. And I understand now that Direct-X independence is the direction of vpinball. And just to clarify, I am not referring to _vpinball_ as a science experiment — only the idea of having full cross-platform functionality. But perhaps that is exactly what you take exception to.

Maybe you can clear this up for me: I have a cabinet with the whole b2s server, etc. — are VPINMame and the B2S server, all the other parts, portable to other platforms? (Honestly I have never got into the PUP-pack thing so don't actually care about that.)

I am not sure if you were talking about this specifically, but I have commented on how complex putting together all the pieces to VPX are — to get the multiple-monitor, b2s thing working. Is that something they are hoping to address? Unless you tell me otherwise, I still believe there are a lot of moving parts to the VPX ecosystem that can be daunting to the newcomer.

I think I have come across the script repo you point out. I should link to it for people visiting the blog that want "to learn more".

Also, I will try the code formatter. I still like the idea though of novices hand-linting code at least once, ha ha.

Anyway, again thank you for the feedback. Keep in mind my audience, but be sure to point out any stupid things I post, ha ha. I am new to this as and expect an even newer audience — but I certainly don't want to send them in the wrong direction.

John Calhoun—

EDIT: and yes, please feel free to continue a dialog about this — either in this "Issue" or the VPX_Resources one if you like.

**Comment by francisdb** [comment]
> Maybe you can clear this up for me: I have a cabinet with the whole b2s server, etc. — are VPINMame and the B2S server, all the other parts, portable to other platforms? (Honestly I have never got into the PUP-pack thing so don't actually care about that.)

VPinball standalone includes a rewritten version of all those parts in a single binary, so no more messing with multiple downloads, putting them in the right place and making sure they are registered correctly. Jason is doing an amazing job there.

Meanwhile I'm rewriting the code formatter at https://github.com/francisdb/vbsfmt
